### ISSUE TITLE
Overcoming limitations

### ISSUE THREAD

**Issue by LukeDefeo** [apstndb/zetasql-sandbox#1]
Hi thanks for this project, i was struggling a lot with getting the build setup using the main repo directly.

In the limitations i can see that _PARTITIONTIME pseudo columns are not supported. Do you have any work arounds in mind that we can explore? 

Is it an issue with the underlying zeta lib or with this sandbox

**Comment by apstndb** [comment]
It's just not implemented in this repository currently.
I think it would be easy to implement using ZetaSQL.

**Comment by apstndb** [comment]
I believe it is supported in https://github.com/apstndb/zetasql-sandbox/commit/41229928e5572cf8ae98e02cfc3e932d277182a2

**Comment by LukeDefeo** [comment]
amazing thank you
